#  Importing Modules

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
# Reading the dataset

df = pd.read_csv("Business Funding Data.csv", encoding="latin1")
df.head(30)

,Website Domain,Effective date,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,NaN,2024-03-14T01:00:00+01:00,NaN,NaN,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,NaN,2024-05-31T02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,NaN,2024-07-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,NaN,2024-05-01T02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,NaN,2024-04-11T02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18T02:00:00+02:00,2024-04-24T02:00:00+02:00,Series B,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16T02:00:00+02:00,2024-04-16T02:00:00+02:00,NaN,NaN,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,NaN,2024-08-07T02:00:00+02:00,Series I,series_i,"[""series_i"", ""venture""]",NaN,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,NaN,2024-07-08T02:00:00+02:00,NaN,NaN,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,NaN,2024-04-18T02:00:00+02:00,NaN,NaN,[],NaN,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,NaN,2024-03-26T01:00:00+01:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,NaN,2024-05-09T02:00:00+02:00,NaN,NaN,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,NaN,2024-07-16T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,NaN,2024-07-15T02:00:00+02:00,NaN,NaN,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,NaN,2024-06-05T02:00:00+02:00,NaN,NaN,[],NaN,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,NaN,2024-06-27T02:00:00+02:00,Series A2,series_a2,"[""series_a2"", ""venture""]",NaN,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,NaN,2024-04-25T02:00:00+02:00,NaN,NaN,[],NaN,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,NaN,2024-04-10T02:00:00+02:00,NaN,NaN,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20T02:00:00+02:00,2024-06-18T02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24T02:00:00+02:00,2024-04-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,NaN,2024-06-25T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26T02:00:00+02:00,2024-06-26T02:00:00+02:00,NaN,NaN,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,NaN,2024-04-30T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27T02:00:00+02:00,2024-06-27T02:00:00+02:00,Series A,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,NaN,2024-05-22T02:00:00+02:00,NaN,NaN,"[""private_equity"", ""venture""]",NaN,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,NaN,2024-06-25T02:00:00+02:00,NaN,NaN,[],NaN,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     object
 1   Effective date             6 non-null      object
 2   Found At                   26 non-null     object
 3   Financing Type             8 non-null      object
 4   Financing Type Normalized  8 non-null      object
 5   Categories                 26 non-null     object
 6   Investors                  13 non-null     object
 7   Investors Count            13 non-null     float64
 8   Amount                     26 non-null     object
 9   Amount Normalized          26 non-null     int64
 10  Source Urls                26 non-null     object
dtypes: float64(1), int64(1), object(9)
memory usage: 2.4+ KB

# Missing Values

In [7]:
# Get total number of entries
len(df)

26

In [8]:
# Determine the percentage of missing values in each column
missing_percentage = df.isnull().sum() / len(df) * 100
missing_percentage

Website Domain                0.000000
Effective date               76.923077
Found At                      0.000000
Financing Type               69.230769
Financing Type Normalized    69.230769
Categories                    0.000000
Investors                    50.000000
Investors Count              50.000000
Amount                        0.000000
Amount Normalized             0.000000
Source Urls                   0.000000
dtype: float64

In [12]:
# Find unique items in the Effective date column
df["Effective date"].unique()

array([nan, '2024-04-18T02:00:00+02:00', '2024-04-16T02:00:00+02:00',
       '2024-06-20T02:00:00+02:00', '2024-04-24T02:00:00+02:00',
       '2024-06-26T02:00:00+02:00', '2024-06-27T02:00:00+02:00'],
      dtype=object)

In [16]:
# Find the most occuring date
df["Effective date"].mode()[0]

'2024-04-16T02:00:00+02:00'

In [18]:
# Fill the missing date with the mode value
df["Effective date"].fillna(df["Effective date"].mode()[0], inplace=True)
df

,Website Domain,Effective date,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-04-16T02:00:00+02:00,2024-03-14T01:00:00+01:00,NaN,NaN,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-04-16T02:00:00+02:00,2024-05-31T02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,2024-04-16T02:00:00+02:00,2024-07-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,2024-04-16T02:00:00+02:00,2024-05-01T02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-16T02:00:00+02:00,2024-04-11T02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18T02:00:00+02:00,2024-04-24T02:00:00+02:00,Series B,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16T02:00:00+02:00,2024-04-16T02:00:00+02:00,NaN,NaN,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,2024-04-16T02:00:00+02:00,2024-08-07T02:00:00+02:00,Series I,series_i,"[""series_i"", ""venture""]",NaN,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,2024-04-16T02:00:00+02:00,2024-07-08T02:00:00+02:00,NaN,NaN,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,2024-04-16T02:00:00+02:00,2024-04-18T02:00:00+02:00,NaN,NaN,[],NaN,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,2024-04-16T02:00:00+02:00,2024-03-26T01:00:00+01:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,2024-04-16T02:00:00+02:00,2024-05-09T02:00:00+02:00,NaN,NaN,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,2024-04-16T02:00:00+02:00,2024-07-16T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,2024-04-16T02:00:00+02:00,2024-07-15T02:00:00+02:00,NaN,NaN,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,2024-04-16T02:00:00+02:00,2024-06-05T02:00:00+02:00,NaN,NaN,[],NaN,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,2024-04-16T02:00:00+02:00,2024-06-27T02:00:00+02:00,Series A2,series_a2,"[""series_a2"", ""venture""]",NaN,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-25T02:00:00+02:00,NaN,NaN,[],NaN,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,2024-04-16T02:00:00+02:00,2024-04-10T02:00:00+02:00,NaN,NaN,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20T02:00:00+02:00,2024-06-18T02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24T02:00:00+02:00,2024-04-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26T02:00:00+02:00,2024-06-26T02:00:00+02:00,NaN,NaN,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-30T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27T02:00:00+02:00,2024-06-27T02:00:00+02:00,Series A,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,2024-04-16T02:00:00+02:00,2024-05-22T02:00:00+02:00,NaN,NaN,"[""private_equity"", ""venture""]",NaN,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,NaN,NaN,[],NaN,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     object
 1   Effective date             26 non-null     object
 2   Found At                   26 non-null     object
 3   Financing Type             8 non-null      object
 4   Financing Type Normalized  8 non-null      object
 5   Categories                 26 non-null     object
 6   Investors                  13 non-null     object
 7   Investors Count            13 non-null     float64
 8   Amount                     26 non-null     object
 9   Amount Normalized          26 non-null     int64
 10  Source Urls                26 non-null     object
dtypes: float64(1), int64(1), object(9)
memory usage: 2.4+ KB

In [25]:
# Fill the missing values with mean value
df["Investors Count"].fillna(df["Investors Count"].mean(), inplace=True)
df

,Website Domain,Effective date,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-04-16T02:00:00+02:00,2024-03-14T01:00:00+01:00,NaN,NaN,[],NaN,1.846154,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-04-16T02:00:00+02:00,2024-05-31T02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.000000,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,2024-04-16T02:00:00+02:00,2024-07-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]",NaN,1.846154,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,2024-04-16T02:00:00+02:00,2024-05-01T02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.000000,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-16T02:00:00+02:00,2024-04-11T02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.000000,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18T02:00:00+02:00,2024-04-24T02:00:00+02:00,Series B,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.000000,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16T02:00:00+02:00,2024-04-16T02:00:00+02:00,NaN,NaN,"[""debt_financing""]",runwaygrowth.com,1.000000,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,2024-04-16T02:00:00+02:00,2024-08-07T02:00:00+02:00,Series I,series_i,"[""series_i"", ""venture""]",NaN,1.846154,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,2024-04-16T02:00:00+02:00,2024-07-08T02:00:00+02:00,NaN,NaN,[],damachotelsandresorts.com,1.000000,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,2024-04-16T02:00:00+02:00,2024-04-18T02:00:00+02:00,NaN,NaN,[],NaN,1.846154,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,2024-04-16T02:00:00+02:00,2024-03-26T01:00:00+01:00,Seed,seed,"[""seed"", ""venture""]",NaN,1.846154,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,2024-04-16T02:00:00+02:00,2024-05-09T02:00:00+02:00,NaN,NaN,[],surocap.com,1.000000,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,2024-04-16T02:00:00+02:00,2024-07-16T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,1.846154,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,2024-04-16T02:00:00+02:00,2024-07-15T02:00:00+02:00,NaN,NaN,[],eib.org,1.000000,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,2024-04-16T02:00:00+02:00,2024-06-05T02:00:00+02:00,NaN,NaN,[],NaN,1.846154,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,2024-04-16T02:00:00+02:00,2024-06-27T02:00:00+02:00,Series A2,series_a2,"[""series_a2"", ""venture""]",NaN,1.846154,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-25T02:00:00+02:00,NaN,NaN,[],NaN,1.846154,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,2024-04-16T02:00:00+02:00,2024-04-10T02:00:00+02:00,NaN,NaN,"[""private_equity""]",vistaragrowth.com,1.000000,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20T02:00:00+02:00,2024-06-18T02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,1.000000,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24T02:00:00+02:00,2024-04-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.000000,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,1.846154,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26T02:00:00+02:00,2024-06-26T02:00:00+02:00,NaN,NaN,"[""private_equity""]",cibc.com,1.000000,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-30T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,1.846154,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27T02:00:00+02:00,2024-06-27T02:00:00+02:00,Series A,series_a,"[""series_a"", ""venture""]",inovia.vc,1.000000,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,2024-04-16T02:00:00+02:00,2024-05-22T02:00:00+02:00,NaN,NaN,"[""private_equity"", ""venture""]",NaN,1.846154,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,NaN,NaN,[],NaN,1.846154,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     object
 1   Effective date             26 non-null     object
 2   Found At                   26 non-null     object
 3   Financing Type             8 non-null      object
 4   Financing Type Normalized  8 non-null      object
 5   Categories                 26 non-null     object
 6   Investors                  13 non-null     object
 7   Investors Count            26 non-null     float64
 8   Amount                     26 non-null     object
 9   Amount Normalized          26 non-null     int64
 10  Source Urls                26 non-null     object
dtypes: float64(1), int64(1), object(9)
memory usage: 2.4+ KB

In [27]:
df["Investors"].unique()

array([nan,
       'avivainvestors.com, lloydsbankinggroup.com, santander.co.uk, swip.com, cibc.com, societegenerale.com, natwest.us, rabobank.com, mufg.jp',
       'stackcapitalgroup.com', 'chevychasetrust.com',
       'alantra.com, blueearth.capital', 'runwaygrowth.com',
       'damachotelsandresorts.com', 'surocap.com', 'eib.org',
       'vistaragrowth.com', 'accelia.vc',
       'edc.ca, desjardinscapital.com, fondsftq.com', 'cibc.com',
       'inovia.vc'], dtype=object)

In [29]:
# Fill the Investors value with nan with mode value
df["Investors"].fillna(df["Investors"].mode()[0], inplace=True)
df

,Website Domain,Effective date,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-04-16T02:00:00+02:00,2024-03-14T01:00:00+01:00,NaN,NaN,[],accelia.vc,1.846154,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-04-16T02:00:00+02:00,2024-05-31T02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.000000,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,2024-04-16T02:00:00+02:00,2024-07-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,1.846154,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,2024-04-16T02:00:00+02:00,2024-05-01T02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.000000,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-16T02:00:00+02:00,2024-04-11T02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.000000,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18T02:00:00+02:00,2024-04-24T02:00:00+02:00,Series B,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.000000,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16T02:00:00+02:00,2024-04-16T02:00:00+02:00,NaN,NaN,"[""debt_financing""]",runwaygrowth.com,1.000000,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,2024-04-16T02:00:00+02:00,2024-08-07T02:00:00+02:00,Series I,series_i,"[""series_i"", ""venture""]",accelia.vc,1.846154,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,2024-04-16T02:00:00+02:00,2024-07-08T02:00:00+02:00,NaN,NaN,[],damachotelsandresorts.com,1.000000,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,2024-04-16T02:00:00+02:00,2024-04-18T02:00:00+02:00,NaN,NaN,[],accelia.vc,1.846154,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,2024-04-16T02:00:00+02:00,2024-03-26T01:00:00+01:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,1.846154,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,2024-04-16T02:00:00+02:00,2024-05-09T02:00:00+02:00,NaN,NaN,[],surocap.com,1.000000,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,2024-04-16T02:00:00+02:00,2024-07-16T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,1.846154,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,2024-04-16T02:00:00+02:00,2024-07-15T02:00:00+02:00,NaN,NaN,[],eib.org,1.000000,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,2024-04-16T02:00:00+02:00,2024-06-05T02:00:00+02:00,NaN,NaN,[],accelia.vc,1.846154,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,2024-04-16T02:00:00+02:00,2024-06-27T02:00:00+02:00,Series A2,series_a2,"[""series_a2"", ""venture""]",accelia.vc,1.846154,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-25T02:00:00+02:00,NaN,NaN,[],accelia.vc,1.846154,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,2024-04-16T02:00:00+02:00,2024-04-10T02:00:00+02:00,NaN,NaN,"[""private_equity""]",vistaragrowth.com,1.000000,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20T02:00:00+02:00,2024-06-18T02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,1.000000,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24T02:00:00+02:00,2024-04-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.000000,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,1.846154,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26T02:00:00+02:00,2024-06-26T02:00:00+02:00,NaN,NaN,"[""private_equity""]",cibc.com,1.000000,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-30T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,1.846154,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27T02:00:00+02:00,2024-06-27T02:00:00+02:00,Series A,series_a,"[""series_a"", ""venture""]",inovia.vc,1.000000,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,2024-04-16T02:00:00+02:00,2024-05-22T02:00:00+02:00,NaN,NaN,"[""private_equity"", ""venture""]",accelia.vc,1.846154,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,NaN,NaN,[],accelia.vc,1.846154,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     object
 1   Effective date             26 non-null     object
 2   Found At                   26 non-null     object
 3   Financing Type             8 non-null      object
 4   Financing Type Normalized  8 non-null      object
 5   Categories                 26 non-null     object
 6   Investors                  26 non-null     object
 7   Investors Count            26 non-null     float64
 8   Amount                     26 non-null     object
 9   Amount Normalized          26 non-null     int64
 10  Source Urls                26 non-null     object
dtypes: float64(1), int64(1), object(9)
memory usage: 2.4+ KB

In [32]:
df["Financing Type"].mode()

0    Seed
Name: Financing Type, dtype: object

In [33]:
df["Financing Type"].fillna(df["Financing Type"].mode()[0], inplace=True)
df

,Website Domain,Effective date,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-04-16T02:00:00+02:00,2024-03-14T01:00:00+01:00,Seed,NaN,[],accelia.vc,1.846154,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-04-16T02:00:00+02:00,2024-05-31T02:00:00+02:00,Seed,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.000000,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,2024-04-16T02:00:00+02:00,2024-07-24T02:00:00+02:00,Seed,NaN,"[""private_equity""]",accelia.vc,1.846154,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,2024-04-16T02:00:00+02:00,2024-05-01T02:00:00+02:00,Seed,NaN,[],stackcapitalgroup.com,1.000000,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-16T02:00:00+02:00,2024-04-11T02:00:00+02:00,Seed,NaN,[],chevychasetrust.com,1.000000,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18T02:00:00+02:00,2024-04-24T02:00:00+02:00,Series B,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.000000,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16T02:00:00+02:00,2024-04-16T02:00:00+02:00,Seed,NaN,"[""debt_financing""]",runwaygrowth.com,1.000000,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,2024-04-16T02:00:00+02:00,2024-08-07T02:00:00+02:00,Series I,series_i,"[""series_i"", ""venture""]",accelia.vc,1.846154,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,2024-04-16T02:00:00+02:00,2024-07-08T02:00:00+02:00,Seed,NaN,[],damachotelsandresorts.com,1.000000,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,2024-04-16T02:00:00+02:00,2024-04-18T02:00:00+02:00,Seed,NaN,[],accelia.vc,1.846154,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,2024-04-16T02:00:00+02:00,2024-03-26T01:00:00+01:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,1.846154,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,2024-04-16T02:00:00+02:00,2024-05-09T02:00:00+02:00,Seed,NaN,[],surocap.com,1.000000,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,2024-04-16T02:00:00+02:00,2024-07-16T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,1.846154,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,2024-04-16T02:00:00+02:00,2024-07-15T02:00:00+02:00,Seed,NaN,[],eib.org,1.000000,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,2024-04-16T02:00:00+02:00,2024-06-05T02:00:00+02:00,Seed,NaN,[],accelia.vc,1.846154,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,2024-04-16T02:00:00+02:00,2024-06-27T02:00:00+02:00,Series A2,series_a2,"[""series_a2"", ""venture""]",accelia.vc,1.846154,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-25T02:00:00+02:00,Seed,NaN,[],accelia.vc,1.846154,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,2024-04-16T02:00:00+02:00,2024-04-10T02:00:00+02:00,Seed,NaN,"[""private_equity""]",vistaragrowth.com,1.000000,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20T02:00:00+02:00,2024-06-18T02:00:00+02:00,Seed,NaN,"[""private_equity""]",accelia.vc,1.000000,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24T02:00:00+02:00,2024-04-24T02:00:00+02:00,Seed,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.000000,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,1.846154,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26T02:00:00+02:00,2024-06-26T02:00:00+02:00,Seed,NaN,"[""private_equity""]",cibc.com,1.000000,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-30T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,1.846154,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27T02:00:00+02:00,2024-06-27T02:00:00+02:00,Series A,series_a,"[""series_a"", ""venture""]",inovia.vc,1.000000,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,2024-04-16T02:00:00+02:00,2024-05-22T02:00:00+02:00,Seed,NaN,"[""private_equity"", ""venture""]",accelia.vc,1.846154,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,Seed,NaN,[],accelia.vc,1.846154,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     object
 1   Effective date             26 non-null     object
 2   Found At                   26 non-null     object
 3   Financing Type             26 non-null     object
 4   Financing Type Normalized  8 non-null      object
 5   Categories                 26 non-null     object
 6   Investors                  26 non-null     object
 7   Investors Count            26 non-null     float64
 8   Amount                     26 non-null     object
 9   Amount Normalized          26 non-null     int64
 10  Source Urls                26 non-null     object
dtypes: float64(1), int64(1), object(9)
memory usage: 2.4+ KB

In [35]:
df["Financing Type Normalized"].fillna(df["Financing Type Normalized"].mode()[0], inplace=True)
df

,Website Domain,Effective date,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-04-16T02:00:00+02:00,2024-03-14T01:00:00+01:00,Seed,seed,[],accelia.vc,1.846154,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-04-16T02:00:00+02:00,2024-05-31T02:00:00+02:00,Seed,seed,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.000000,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,2024-04-16T02:00:00+02:00,2024-07-24T02:00:00+02:00,Seed,seed,"[""private_equity""]",accelia.vc,1.846154,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,2024-04-16T02:00:00+02:00,2024-05-01T02:00:00+02:00,Seed,seed,[],stackcapitalgroup.com,1.000000,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-16T02:00:00+02:00,2024-04-11T02:00:00+02:00,Seed,seed,[],chevychasetrust.com,1.000000,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18T02:00:00+02:00,2024-04-24T02:00:00+02:00,Series B,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.000000,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16T02:00:00+02:00,2024-04-16T02:00:00+02:00,Seed,seed,"[""debt_financing""]",runwaygrowth.com,1.000000,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,2024-04-16T02:00:00+02:00,2024-08-07T02:00:00+02:00,Series I,series_i,"[""series_i"", ""venture""]",accelia.vc,1.846154,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,2024-04-16T02:00:00+02:00,2024-07-08T02:00:00+02:00,Seed,seed,[],damachotelsandresorts.com,1.000000,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,2024-04-16T02:00:00+02:00,2024-04-18T02:00:00+02:00,Seed,seed,[],accelia.vc,1.846154,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,2024-04-16T02:00:00+02:00,2024-03-26T01:00:00+01:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,1.846154,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,2024-04-16T02:00:00+02:00,2024-05-09T02:00:00+02:00,Seed,seed,[],surocap.com,1.000000,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,2024-04-16T02:00:00+02:00,2024-07-16T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,1.846154,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,2024-04-16T02:00:00+02:00,2024-07-15T02:00:00+02:00,Seed,seed,[],eib.org,1.000000,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,2024-04-16T02:00:00+02:00,2024-06-05T02:00:00+02:00,Seed,seed,[],accelia.vc,1.846154,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,2024-04-16T02:00:00+02:00,2024-06-27T02:00:00+02:00,Series A2,series_a2,"[""series_a2"", ""venture""]",accelia.vc,1.846154,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-25T02:00:00+02:00,Seed,seed,[],accelia.vc,1.846154,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,2024-04-16T02:00:00+02:00,2024-04-10T02:00:00+02:00,Seed,seed,"[""private_equity""]",vistaragrowth.com,1.000000,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20T02:00:00+02:00,2024-06-18T02:00:00+02:00,Seed,seed,"[""private_equity""]",accelia.vc,1.000000,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24T02:00:00+02:00,2024-04-24T02:00:00+02:00,Seed,seed,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.000000,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,1.846154,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26T02:00:00+02:00,2024-06-26T02:00:00+02:00,Seed,seed,"[""private_equity""]",cibc.com,1.000000,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-30T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,1.846154,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27T02:00:00+02:00,2024-06-27T02:00:00+02:00,Series A,series_a,"[""series_a"", ""venture""]",inovia.vc,1.000000,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,2024-04-16T02:00:00+02:00,2024-05-22T02:00:00+02:00,Seed,seed,"[""private_equity"", ""venture""]",accelia.vc,1.846154,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,Seed,seed,[],accelia.vc,1.846154,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     object
 1   Effective date             26 non-null     object
 2   Found At                   26 non-null     object
 3   Financing Type             26 non-null     object
 4   Financing Type Normalized  26 non-null     object
 5   Categories                 26 non-null     object
 6   Investors                  26 non-null     object
 7   Investors Count            26 non-null     float64
 8   Amount                     26 non-null     object
 9   Amount Normalized          26 non-null     int64
 10  Source Urls                26 non-null     object
dtypes: float64(1), int64(1), object(9)
memory usage: 2.4+ KB

# Handle Duplicate

In [37]:
# Find duplicates 
duplicates = df.duplicated().sum()
print(f"\nNumber of duplicate rows: {duplicates}")

Number of duplicate rows: 0

In [38]:
# Find the statistic calculation
df.describe()

       Investors Count  Amount Normalized
count        26.000000       2.600000e+01
mean          1.846154       2.264687e+08
std           1.545216       5.383239e+08
min           1.000000       1.600000e+06
25%           1.000000       4.685750e+06
50%           1.846154       1.160000e+07
75%           1.846154       4.750000e+07
max           9.000000       2.000000e+09

# Convert string data to labels

In [39]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [40]:
# List of categorical columns to encode
categorical_cols = ["Investors", "Source Urls", "Categories", "Financing Type Normalized", 'Financing Type', "Website Domain"]

# Applly Label Encoding to each categorical columns
for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

In [41]:
df

,Website Domain,Effective date,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,18,2024-04-16T02:00:00+02:00,2024-03-14T01:00:00+01:00,0,0,8,0,1.846154,$1.9b,1900000000,25
1,19,2024-04-16T02:00:00+02:00,2024-05-31T02:00:00+02:00,0,0,8,2,9.000000,$522.7 million,522700000,5
2,19,2024-04-16T02:00:00+02:00,2024-07-24T02:00:00+02:00,0,0,2,0,1.846154,£41.7m,53671000,17
3,2,2024-04-16T02:00:00+02:00,2024-05-01T02:00:00+02:00,0,0,8,10,1.000000,US$8 million,8000000,16
4,8,2024-04-16T02:00:00+02:00,2024-04-11T02:00:00+02:00,0,0,8,3,1.000000,$1.96 million,1960000,10
5,15,2024-04-18T02:00:00+02:00,2024-04-24T02:00:00+02:00,3,3,6,1,2.000000,$27.2 Million,27200000,20
6,3,2024-04-16T02:00:00+02:00,2024-04-16T02:00:00+02:00,0,0,0,9,1.000000,$40 million,40000000,22
7,5,2024-04-16T02:00:00+02:00,2024-08-07T02:00:00+02:00,4,4,7,0,1.846154,$685 million,685000000,3
8,0,2024-04-16T02:00:00+02:00,2024-07-08T02:00:00+02:00,0,0,8,5,1.000000,$50mn,50000000,8
9,7,2024-04-16T02:00:00+02:00,2024-04-18T02:00:00+02:00,0,0,8,0,1.846154,AU$10.7M,6865000,9
10,11,2024-04-16T02:00:00+02:00,2024-03-26T01:00:00+01:00,0,0,3,0,1.846154,$6.7 million,6700000,15
11,2,2024-04-16T02:00:00+02:00,2024-05-09T02:00:00+02:00,0,0,8,11,1.000000,$2 billion,2000000000,18
12,16,2024-04-16T02:00:00+02:00,2024-07-16T02:00:00+02:00,0,0,3,0,1.846154,Û4.2 million,4581000,6
13,20,2024-04-16T02:00:00+02:00,2024-07-15T02:00:00+02:00,0,0,8,7,1.000000,Û425 million,464695000,7
14,14,2024-04-16T02:00:00+02:00,2024-06-05T02:00:00+02:00,0,0,8,0,1.846154,$10M,10000000,13
15,6,2024-04-16T02:00:00+02:00,2024-06-27T02:00:00+02:00,2,2,5,0,1.846154,USD 31M,31000000,11
16,1,2024-04-16T02:00:00+02:00,2024-04-25T02:00:00+02:00,0,0,8,0,1.846154,$5M,5000000,23
17,4,2024-04-16T02:00:00+02:00,2024-04-10T02:00:00+02:00,0,0,2,12,1.000000,$24.6 million CAD,18139000,1
18,10,2024-06-20T02:00:00+02:00,2024-06-18T02:00:00+02:00,0,0,2,0,1.000000,$1.6M,1600000,21
19,12,2024-04-24T02:00:00+02:00,2024-04-24T02:00:00+02:00,0,0,2,6,3.000000,$17.4 million,17400000,4
20,17,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,0,0,3,0,1.846154,CAD$2.5M,1823000,14
21,4,2024-06-26T02:00:00+02:00,2024-06-26T02:00:00+02:00,0,0,2,4,1.000000,$10 million,10000000,19
22,1,2024-04-16T02:00:00+02:00,2024-04-30T02:00:00+02:00,0,0,3,0,1.846154,$5 million CAD,3653000,0
23,9,2024-06-27T02:00:00+02:00,2024-06-27T02:00:00+02:00,1,1,4,8,1.000000,US$13.2M,13200000,2
24,13,2024-04-16T02:00:00+02:00,2024-05-22T02:00:00+02:00,0,0,1,0,1.846154,$2.5M,2500000,12
25,17,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,0,0,8,0,1.846154,$2.5m,2500000,24